name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ARM target
        run: rustup target add armv7-unknown-linux-gnueabihf
      - name: Build for x86_64
        run: cargo build --verbose --release --target x86_64-unknown-linux-gnu
      - name: Build for ARMv7
        run: |
          export PKG_CONFIG_ALLOW_CROSS=1
          export PKG_CONFIG_PATH=/usr/lib/arm-linux-gnueabihf/pkgconfig
          export PKG_CONFIG_LIBDIR=/usr/lib/arm-linux-gnueabihf/pkgconfig
          export PKG_CONFIG_SYSROOT_DIR=/usr/arm-linux-gnueabihf
          cargo build --verbose --release --target armv7-unknown-linux-gnueabihf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-gnu/release/musicbox
            target/armv7-unknown-linux-gnueabihf/release/musicbox